### ISSUE TITLE
Solve Javaparser Import problem

### ISSUE THREAD

**Issue by Blum-P** [Hassan-smaoui/e4CompareFramework-team3#3]
Gradle?

**Comment by paulo-haas** [comment]
Installation guide https://github.com/javaparser/javaparser

**Comment by paulo-haas** [comment]
This issue has been solved by commit [da6ef61](https://github.com/Hassan-smaoui/e4CompareFramework-team3/commit/da6ef61eff9ad5c5edc9cce865a7f1290820399c)
